### ISSUE TITLE
跑通代码后image文件夹为空

### ISSUE THREAD

**Issue by liangfeifan** [river-huang/ARWGAN#12]
**image**文件相关保存的操作被注释掉了 ，将注释的操作取消注释后似乎无法正常输出图片，这是报错：
Traceback (most recent call last):
  File "G:\ARWGAN-main\main.py", line 148, in <module>
    main()
  File "G:\ARWGAN-main\main.py", line 144, in main
    train(model, device, net_config, train_options, this_run_folder, tb_logger)        
  File "G:\ARWGAN-main\train.py", line 75, in train
    utils.save_images(image.cpu()[:images_to_save, :, :, :],
  File "G:\ARWGAN-main\utils.py", line 62, in save_images
    torchvision.utils.save_image(stacked_images, filename, format= original_images.shape[0], normalize=False)
  File "E:\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\lib\site-packages\torchvision\utils.py", line 151, in save_image
    im.save(fp, format=format)
  File "C:\Users\tudou\AppData\Roaming\Python\Python310\site-packages\PIL\Image.py", line 2335, in save
    if format.upper() not in SAVE:
**AttributeError: 'int' object has no attribute 'upper'**
请问是否方便分享可跑通的代码呢？

**Comment by JJassy** [comment]
请问您解决了吗

**Comment by OpenAscent-L** [comment]
请问加了噪声之后的水印还鲁棒吗？为什么我加了噪声之后的水印提取率接近百分之五十？

**Comment by Ppinkie** [comment]
请问解决了吗
